name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > todo-key.pem
        chmod 600 todo-key.pem
        mkdir -p ~/.ssh
        
        # Create known_hosts file if it doesn't exist
        ssh-keyscan -H ec2-3-89-23-13.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        
        # Use todo-key.pem instead of keyfile
        ssh -t -i todo-key.pem ubuntu@ec2-3-89-23-13.compute-1.amazonaws.com "sudo bash ~/deploy.sh"
